# Generated by Django 3.1.2 on 2021-07-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0131_auto_20210713_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_num_id',
            field=models.IntegerField(default='123'),
        ),
    ]
