# Generated by Django 3.1.2 on 2021-08-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0132_product_item_num_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_num_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mpn',
        ),
    ]
