# Generated by Django 3.1.2 on 2021-12-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0133_auto_20210812_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='featured_product',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
