# Generated by Django 3.1.2 on 2021-12-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0133_auto_20210812_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeproduct',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
