# Generated by Django 3.1.2 on 2021-08-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='item_num_id',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='mpn',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='source',
        ),
        migrations.AddField(
            model_name='offer',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='offer',
            name='date_added',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='date_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='type',
            field=models.CharField(blank=True, choices=[('excess_list', 'Excess List'), ('stock_list', 'Stock List'), ('vendor_offer', 'Vendor Offer'), ('rms_offfer', 'RMS Offer'), ('po', 'PO')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='vendor_region',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='vendor_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='lead_time_days',
            field=models.IntegerField(default=-1),
        ),
    ]
