# Generated by Django 3.1.2 on 2021-10-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_transaction_searchable_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
