# Generated by Django 3.1.2 on 2021-11-18 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now=True)),
                ('updated_date', models.DateField()),
                ('roketchip_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(max_length=50)),
                ('mcode', models.CharField(max_length=50)),
                ('master_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('partlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_list.partlist')),
            ],
        ),
    ]
