# Generated by Django 3.1.2 on 2021-11-23 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lists_name', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now=True)),
                ('updated_date', models.DateField(null=True)),
                ('rocketchip_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='parts',
            name='partlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_list.partlists'),
        ),
        migrations.DeleteModel(
            name='PartList',
        ),
    ]
