# Generated by Django 3.1.2 on 2021-11-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partlist',
            name='updated_date',
            field=models.DateField(null=True),
        ),
    ]
