version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@0.0.10
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  frontend-deploy:
    executor:
      name: aws-cli/default
      python-version: "3.7-node"
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: "647697256804"
      - run: aws --version
      - run: aws s3 ls
      - run: chmod +x ./deploy-frontend.sh
      - run: ./deploy-frontend.sh
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          path: ./saleor
          dockerfile: ./Dockerfile
          account-url: AWS_ECR_ACCOUNT_URL
          repo: "fusion-online-core-services-sandbox"
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: api
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: "core-services"
          cluster-name: "fusion-online-ecs-cluster-sandbox"
          service-name: "core-services"
          container-image-name-updates: "container=core-services,tag=${CIRCLE_SHA1}"
          filters:
            branches:
              only: api
  build:
    jobs:
      - frontend-deploy:
          filters:
            branches:
              only: api
