# Generated by Django 3.1.2 on 2021-08-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='tariff',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
