# Generated by Django 3.1.2 on 2021-08-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0002_offer_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(blank=True, choices=[('EXCESS_LIST', 'Excess List'), ('STOCK_LIST', 'Stock List'), ('VENDOR_OFFER', 'Vendor Offer'), ('RMS_OFFER', 'RMS Offer'), ('PO', 'PO')], default='', max_length=50),
        ),
    ]
