# Generated by Django 3.1.2 on 2021-08-10 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20200810_1415'),
        ('fusion_online', '0004_auto_20210809_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(blank=True, max_length=256)),
                ('ship_to_name', models.CharField(blank=True, max_length=256)),
                ('ship_via', models.CharField(blank=True, max_length=256)),
                ('vat_id', models.CharField(blank=True, max_length=256)),
                ('ship_to_num', models.IntegerField(blank=True, max_length=256)),
                ('validation_message', models.CharField(blank=True, max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('address', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.address')),
            ],
        ),
    ]
