# Generated by Django 3.1.2 on 2021-08-10 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fusion_online', '0004_auto_20210809_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RFQLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(max_length=50)),
                ('mcode', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('target', models.FloatField()),
                ('date_code', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=500)),
                ('cipn', models.CharField(max_length=50)),
                ('commodity_code', models.CharField(choices=[('DEFAULT', 'Default'), ('TBD', 'TBD')], max_length=50)),
                ('offer_id', models.IntegerField()),
                ('rfq_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fusion_online.rfqsubmission')),
            ],
        ),
    ]
