# Generated by Django 3.1.2 on 2021-08-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0005_rfqlineitem_rfqsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqlineitem',
            name='commodity_code',
            field=models.CharField(choices=[('CPU_SERVER_INTEL', 'CPU Server-Intel'), ('CPU_SERVER_AMD_EPYC', 'CPU Server-AMD EPYC'), ('CPU_DESKTOP_INTEL', 'CPU Desktop-Intel'), ('CPU_DESKTOP_AMD_RYZEN_MOBILE_CPU', 'CPU Desktop-AMD Ryzen Mobile CPU'), ('CPU_INTEL', 'CPU-Intel'), ('MEM_SERVER_DIMM', 'Memory-Server DIMM'), ('MEM_GDDR', 'Memory-GDDR'), ('MEM_DRAM', 'Memory-DRAM'), ('MEM_PC_DIMM', 'Memory-PC DIMM'), ('GPU_ENTERPRISE', 'GPU-Enterprise'), ('GPU_CONSUMER', 'GPU-Consume'), ('STOR_SOLID_STATE_DRIVES', 'Storage-Solid State Drives')], max_length=50),
        ),
    ]
