# Generated by Django 3.1.2 on 2021-08-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0005_shippingaddress'),
        ('fusion_online', '0006_auto_20210810_1733'),
    ]

    operations = [
    ]
