# Generated by Django 3.1.2 on 2021-08-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0007_merge_20210811_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='coo',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='offer',
            name='vendor_region',
            field=models.CharField(blank=True, choices=[('USA', 'USA'), ('ASIA_PACIFIC', 'Asia/Pacific'), ('ASIA', 'Asia'), ('EMEA', 'EMEA'), ('EUROPE', 'Europe'), ('OTHER', 'Other')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='vendor_type',
            field=models.CharField(blank=True, choices=[('UNCLASSIFIED', 'Unclassified'), ('BROKER', 'Broker'), ('MFG_DIRECT', 'Mfg. Direct'), ('OEM_CM_EXCESS', 'OEM/CM Excess'), ('AUTHORIZED_FRANCHISE', 'Authorized/Franchise'), ('EXPENSE_NON_PRODUCT', 'Expense (non-product)'), ('SERVICE', 'Service')], default='', max_length=50),
        ),
    ]
