# Generated by Django 3.1.2 on 2021-08-18 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20200810_1415'),
        ('fusion_online', '0009_rfqresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_to_address', to='account.address'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='ship_to_num',
            field=models.IntegerField(blank=True),
        ),
    ]
