# Generated by Django 3.1.2 on 2021-08-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0010_auto_20210818_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='ship_to_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
