# Generated by Django 3.1.2 on 2021-08-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0011_auto_20210819_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='ship_to_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='ship_via',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='validation_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='vat_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
