# Generated by Django 3.1.2 on 2021-09-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0012_auto_20210823_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqlineitem',
            name='commodity_code',
            field=models.IntegerField(choices=[(1000, 'CPU_SERVER_INTEL'), (1004, 'CPU_SERVER_AMD_EPYC'), (1006, 'CPU_DESKTOP_INTEL'), (1007, 'CPU_DESKTOP_AMD_RYZEN_MOBILE_CPU'), (1008, 'CPU_INTEL'), (1001, 'MEM_SERVER_DIMM'), (1002, 'MEM_GDDR'), (1003, 'MEM_DRAM'), (1009, 'MEM_PC_DIMM'), (1010, 'GPU_ENTERPRISE'), (1011, 'GPU_CONSUMER'), (1005, 'STOR_SOLID_STATE_DRIVES')]),
        ),
    ]
