# Generated by Django 3.1.2 on 2021-09-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0012_auto_20210823_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='date_added',
            field=models.BigIntegerField(null=True),
        ),
    ]
