# Generated by Django 3.1.2 on 2021-09-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0013_auto_20210914_1800'),
        ('fusion_online', '0013_auto_20210903_1854'),
    ]

    operations = [
    ]
