# Generated by Django 3.1.2 on 2021-09-17 14:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0133_auto_20210812_1739'),
        ('fusion_online', '0014_merge_20210914_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number', models.BigIntegerField()),
                ('type', models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('BROKER', 'Broker'), ('MFG_DIRECT', 'Mfg. Direct'), ('OEM_CM_EXCESS', 'OEM/CM Excess'), ('AUTHORIZED_FRANCHISE', 'Authorized/Franchise'), ('EXPENSE_NON_PRODUCT', 'Expense (non-product)'), ('SERVICE', 'Service')], max_length=50)),
                ('region', models.CharField(choices=[('USA', 'USA'), ('ASIA_PACIFIC', 'Asia/Pacific'), ('ASIA', 'Asia'), ('EMEA', 'EMEA'), ('EUROPE', 'Europe'), ('OTHER', 'Other')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='vendor_region',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='vendor_type',
        ),
        migrations.AddField(
            model_name='offer',
            name='item_num_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='mcode',
            field=models.CharField(default='string', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='mpn',
            field=models.CharField(default='string', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name=django.core.validators.MinValueValidator(limit_value=0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='product_variant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productvariant'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='tariff_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='fusion_online.vendor'),
        ),
    ]
