# Generated by Django 3.1.2 on 2021-09-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0015_auto_20210917_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='name',
            new_name='vendor_name',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='number',
            new_name='vendor_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='region',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='type',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_region',
            field=models.CharField(choices=[('USA', 'USA'), ('ASIA_PACIFIC', 'Asia/Pacific'), ('ASIA', 'Asia'), ('EMEA', 'EMEA'), ('EUROPE', 'Europe'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('BROKER', 'Broker'), ('MFG_DIRECT', 'Mfg. Direct'), ('OEM_CM_EXCESS', 'OEM/CM Excess'), ('AUTHORIZED_FRANCHISE', 'Authorized/Franchise'), ('EXPENSE_NON_PRODUCT', 'Expense (non-product)'), ('SERVICE', 'Service')], max_length=50, null=True),
        ),
    ]
