# Generated by Django 3.1.2 on 2021-09-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0016_auto_20210917_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
