# Generated by Django 3.1.2 on 2021-09-17 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0017_auto_20210917_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='coo',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date_added',
            field=models.BigIntegerField(default=123456789),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='date_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='lead_time_days',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(limit_value=-1)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='mcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_price',
            field=models.DecimalField(decimal_places=5, max_digits=14),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(limit_value=1)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='tariff_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('EXCESS_LIST', 'Excess List'), ('STOCK_LIST', 'Stock List'), ('VENDOR_OFFER', 'Vendor Offer'), ('RMS_OFFER', 'RMS Offer'), ('PO', 'PO')], max_length=50),
        ),
    ]
