# Generated by Django 3.1.2 on 2021-09-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0020_auto_20210917_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='coo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('Excess List', 'Excess List'), ('Stock List', 'Stock List'), ('Vendor Offer', 'Vendor Offer'), ('RMS Offer', 'RMS Offer'), ('RMS PO', 'RMS PO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_region',
            field=models.CharField(choices=[('Americas', 'Americas'), ('Asia/Pacific', 'Asia/Pacific'), ('EMEA', 'EMEA'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('Unclassified', 'Unclassified'), ('Broker', 'Broker'), ('Mfg. Direct', 'Mfg. Direct'), ('OEM/CM Excess', 'OEM/CM Excess'), ('Authorized/Franchise', 'Authorized/Franchise'), ('Expense (non-product)', 'Expense (non-product)'), ('Service', 'Service')], max_length=50),
        ),
    ]
