# Generated by Django 3.1.2 on 2021-09-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0021_auto_20210923_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfqlineitem',
            old_name='offer_id',
            new_name='rms_response_id',
        ),
        migrations.RenameField(
            model_name='rfqresponse',
            old_name='offer_id',
            new_name='rms_response_id',
        ),
        migrations.AlterField(
            model_name='rfqresponse',
            name='lead_time_days',
            field=models.CharField(max_length=50),
        ),
    ]
