# Generated by Django 3.1.2 on 2021-09-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0022_auto_20210923_1758'),
        ('fusion_online', '0022_auto_20210920_1527'),
    ]

    operations = [
    ]
