# Generated by Django 3.1.2 on 2021-09-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0024_auto_20210923_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqlineitem',
            name='rms_response_id',
            field=models.IntegerField(null=True),
        ),
    ]
