# Generated by Django 3.1.2 on 2021-10-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0025_auto_20210930_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqlineitem',
            name='commodity_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=100),
        ),
    ]
