# Generated by Django 3.1.2 on 2021-10-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0133_auto_20210812_1739'),
        ('fusion_online', '0026_auto_20211006_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='products',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
