# Generated by Django 3.1.2 on 2021-10-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0133_auto_20210812_1739'),
        ('fusion_online', '0027_vendor_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='products',
            field=models.ManyToManyField(null=True, to='product.Product'),
        ),
    ]
