# Generated by Django 3.1.2 on 2021-10-25 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0029_auto_20211020_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqresponse',
            name='date_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rfqresponse',
            name='quantity',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
