# Generated by Django 3.1.2 on 2021-11-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0030_auto_20211025_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='INITIATED', max_length=50)),
                ('message', models.JSONField(null=True)),
                ('user_id', models.CharField(blank=True, max_length=200)),
                ('rows_included', models.IntegerField(null=True)),
                ('rows_successfully_processed', models.IntegerField(null=True)),
                ('type', models.CharField(choices=[('PRODUCT', 'Product')], default='PRODUCT', max_length=50)),
            ],
        ),
    ]
