# Generated by Django 3.1.2 on 2021-11-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0030_auto_20211025_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfqresponse',
            old_name='rms_response_id',
            new_name='rms_quote_detail_id',
        ),
    ]
