# Generated by Django 3.1.2 on 2021-11-22 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fusion_online', '0032_auto_20211116_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lists_name', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now=True)),
                ('updated_date', models.DateField(null=True)),
                ('rocketchip_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
