# Generated by Django 3.1.2 on 2021-11-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_online', '0033_partlists'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartLists',
        ),
    ]
