# Generated by Django 3.1.2 on 2021-08-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_auto_20210824_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='ship_to_num',
        ),
    ]
